### ISSUE TITLE
UI blocks on selecting ecosystem and associated warning are logged

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/fb-osmose-bridge#136]
When selecting "iceland shelf/sea" in first page of fin-casey.github.io/wizard , the page appears unresponsive. Also, when the ecosystem is selected, the following warning is logged in the browser console -
```
jquery.min.js:4 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
```

Suggest to implement asynchronous requests for *all* wizard interactions. 

@FIN-casey please let know if you have questions about this.

**Comment by FIN-casey** [comment]
When all the requests are in asynchronous, depends on the amount of data, the display of data will not appear immediately after going to next step.

For example, when the user is using the wizard for the first time and he selected "Iceland shelf/sea" and he proceeded to the next step, the functional group table won't display the contents immediately because it is still processing in the background.

I implement all the request in asynchronous, i think we need to add new text/message that will notify the user that the request is being processed in the background. 

Please test and verify.

**Comment by FIN-casey** [comment]
@agruss2, can you do the test to see if there is an impact in the user experience?
Thanks

**Comment by agruss2** [comment]
@FIN-casey I ran several tests on different computers, using different web browsers, and I did not face the issue mentioned by @jhpoelen. I suggest we close this issue, if that's good for your guys. Many thanks.

**Comment by jhpoelen** [comment]
Thanks @FIN-casey for implementing the asynchronous calls. I think it would be wise to include status messages (e.g., "accessing [Iceland Sea/Shelf] configuration ...") and only enable the "proceed" button if a selection has been made and a configuration is available.

**Comment by FIN-JBarile** [comment]
@agruss2 Is above item from Jorrit the remaining task for this issue? Please confirm for @FIN-casey. Thanks!

**Comment by agruss2** [comment]
@FIN-JBarile @FIN-casey I ran several tests on different computers, using different web browsers, and I did not face the issue mentioned above. Therefore, I am deciding to close the present GitHub isue. Many thanks.
