### ISSUE TITLE
Providing estimates for critical predation efficiency

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/fb-osmose-bridge#25]
Question: Currently, in all OSMOSE applications, the critical predation efficiency of all focal functional groups is set to 0.57, while the maximum starvation mortality of all focal functional groups is set to 0.3 year-1. Could the bridge between FishBase/SeaLifeBase and OSMOSE provide estimates for these two parameters? Should we actually try to make the bridge provide estimates for these two parameters? More generally, should we restrict the number of parameter types for which the bridge between FishBase/SeaLifeBase and OSMOSE provide estimates?

**Comment by jhpoelen** [comment]
see https://github.com/jhpoelen/fb-osmose-bridge/wiki/OSMOSE#ingestion-rate for documentation on this topic.

**Comment by agruss2** [comment]
The question above is primarily addressed to Deng and Skit.

**Comment by agruss2** [comment]
@FIN-JBarile @Dengaloo
I am now clear how we could estimate the critical predation efficiency of focal functional groups using the bridge between FishBase/SeaLifeBase and OSMOSE (see jhpoelen/fb-osmose-bridge/blob/master/src/main/resources/com/github/jhpoelen/fbob/fishbase-mapping.csv).
On the other hand, I am still unclear whether and how the maximum starvation mortality rate of focal functional groups could be obtained through the bridge between FishBase/SeaLifeBase and OSMOSE. I have reviewed the content of all FishBase tables (ropensci/fishbaseapi/tree/master/docs/docs-sources) and the only way we could possibly obtain an estimate for maximum starvation mortality rates would be to equate the maximum starvation mortality rate of a given focal functional group to the Mortality parameter provided in FishBase's popqb.csv. However, the "Mortality" parameter in FishBase's popqb.csv is the "mortality of juveniles and adults (/y) used for simulating age-structured population". Thus, I think that the maximum starvation mortality rate of focal functional groups would be substantially overestimated if we equated it to the Mortality parameter provided in FishBase's popqb.csv. 
Therefore, I think that it would be best to keep the maximum starvation mortality of all focal functional groups to its default value (0.3 year-1) and not try to update this OSMOSE parameter using the bridge between FishBase/SeaLifeBase and OSMOSE. 
Please let me know what you think.

**Comment by Dengaloo** [comment]
I think that Arnaud is right, we would not be able to estimate this parameter from  FishBase or SeaLifeBase tables.

**Comment by agruss2** [comment]
@Dengaloo I agree that it will not be possible for the bridge to provide starvation mortality rate estimates to the user. Therefore, the bridge will set the starvation mortality rate of all functional groups to its default value (i.e., 0.3 year-1). 
Now, regarding critical predation efficiency – In OSMOSE, “critical predation efficiency” is the predation efficiency ensuring body maintenance. This parameter is usually set to 0.57 for all focal functional groups in OSMOSE models. However, a value for this parameter could easily be estimated by the bridge as follows: (1) the MaintQB and PopQB parameters are extracted from FishBase's popqb.csv file; and (2) critical predation efficiency is calculated as the ratio of MaintQB over PopQB. 
Do you agree with all this?

**Comment by Dengaloo** [comment]
@agruss2 : yes we can get the MaintQB from the POPQB table. But note that this is only for a 100 species. But, we can generalize.

**Comment by agruss2** [comment]
@Dengaloo Yes, some sort of generalization would be excellent. 
Then, if MaintQB is missing for one giving species, we can use the MaintQB of a related species or the "critical predation efficiency" of a related species. 
Which of these two options would be easier to implement? 
Would it be doable to populate the FishBase/SeaLifeBase tabs directly, so that the bridge can access estimates of MaintQB or "critical predation efficiency" for a very large number of marine organisms, without having to implement some kind of algorithms to determine the relatedness between species listed by the bridge and other species?

**Comment by Dengaloo** [comment]
@agruss2 : we can create a table instead of filling in the POPQB table because we only encode observed data in tables. i think best to estimate MaintQB for related species in a functional group. Doable. Let me do the Amax thing first, then I will turn my attention to this one.

**Comment by agruss2** [comment]
@Dengaloo I agree that the best option is the option you chose, i.e., if MaintQB is missing for one giving species, we se the MaintQB of a related species.

**Comment by Dengaloo** [comment]
@agruss2 : ok, I forgot something about Q/B, I already have an empirical model that calculates Q/B (the one that was from my thesis and used in Ecopath). If we used that empirical model, we can estimate MaintQB from the QB from this formula.

**Comment by agruss2** [comment]
@Dengaloo I am not sure that I understand your last comment. 
Critical predation efficiency should be calculated as the ratio of MaintQB over PopQB. 
MaintQB and PopQB are two distinct Q/B's. 
Do you mean that you, for your thesis, you developed one empirical model that calculates MaintQB; and another empirical model that calculates PopQB? 
My understanding was that: (1) for your thesis, you developed one empirical model that calculates  PopQB, and PopQB is available for a large number of species in FishBase/SealifeBase; (2) by contrast, MaintQB is available for only 100 species and we do not have an empirical model for MaintQB, such that, f MaintQB is missing for one given species, the bridge between FishBase/SealifeBase and OSMOSE will use the MaintQB of a related species.
Could you please clarify all this? 
Sorry if I made some confusions here!

**Comment by agruss2** [comment]
@Dengaloo Please address my comment above, so that I can be clear as to what you are envisioning here.

**Comment by Dengaloo** [comment]
@agruss2 : yes I based my POPQB equation on those 100 species that are available in the database right now. however, there is a part of the hypothesis that deals with estimating MAINTQB from the POPQB given Winfinity, basically we can use the equation to estimate POPQB if we know the Winfinity, K, temperature in Kelvin, and what the prey items are (carnivore, herbivore, etc.) and an indicator of the metabolic rate. Basically, what I am trying to say is that it is not the related species that is more important if we want to calculate POPQB or MAINTQB, it is the relationship of these parameters that is important, and thus, a 1000 g carnivorous fish with a forked tail would be more similar in maintenance QB to an 800 g omnivorous fish that swims like a cruiser per g of food taken in and per g of food turned to flesh, even if their functional or taxonomic groups are different. We should therefore try to avoid making the replacements of POPQB and MAINTQB using functional or taxonomic groups. We have to use the input parameters for the empirical equation and use those to estimate POPQB and estimate MAINTQB by fraction.

**Comment by agruss2** [comment]
@Dengaloo I agree, this is the way to go.

**Comment by Dengaloo** [comment]
@agruss2 : we implement the empirical equation, correct? do you have it?

**Comment by Dengaloo** [comment]
@agruss2 : please see the last line of the life history tool in FishBase: http://www.fishbase.org/popdyn/KeyfactsSummary_1.php?ID=6470&GenusName=Epinephelus&SpeciesName=marginatus&vStockCode=6792&fc=289

Skit will be able to give you the algorithm that is used for Q/B to be calculated given the parameters selected. Maintenance Q/B is equivalent to the Q/B at Winf, I can send you the graph that shows how it is estimated.

**Comment by agruss2** [comment]
@Dengaloo @FIN-JBarile Many thanks for this!

Could you please send me (for example through Dropbox)? 
**(1)** All of the code to calculate Q/B (if I understood well, this is all of the code that implements the calculation at the last line of the life history tool in FishBase: http://www.fishbase.org/popdyn/KeyfactsSummary_1.php?ID=6470&GenusName=Epinephelus&SpeciesName=marginatus&vStockCode=6792&fc=289)

and 

**(2)** All of the code to calculate Maintenance Q/B (if I understood well, this code is derived from the code to calculate Q/B). 

Once I have all of this information, I will be able to close the present issue and to open a new issue for Jorrit so that the API performs the calculation of critical predation efficiency.

**Comment by Dengaloo** [comment]
@agruss2 and @FIN-JBarile 

I think we can actually add Q/B to the estimate table. Because all the necessary parameters are in FishBase, including the aspect ratio of the caudal fin. If Skit can add the fields QB and MaintQB in the ESTIMATE table, then all Jorrit needs to do is extract those from the ESTIMATE table.

Skit can you comment on this please?

We can use the preferred temperature transformed to Kelvin for the empirical equation and the trophic level as an indication of carnivory. I think this is a more standardized way, something that will be empirically driven and would then not need any user input.

**Comment by agruss2** [comment]
@Dengaloo I really like your idea! This will greatly simplify things. 
@FIN-JBarile If you agree with this plan, please let me know when the fields QB and MaintQB have been added to the ESTIMATE table; I will then close the present issue, update the fishbase-mapping.csv file, and open a new issue for Jorrit so that the API calculates critical predation efficiencies.

**Comment by Dengaloo** [comment]
@agruss2 : please note that this will work only for fish, so you will have QB and MaintQB only for fish. I have not studied the relationship of the underlying parameters for invertebrates, though I doubt that the principles of hydrodynamics will change for invertebrates. I have not collated the same data for invertebrates as of yet.

so are you OK that this is only for fish?

**Comment by agruss2** [comment]
@Dengaloo No problem, I will acknowledge this in the README file that is provided to the user; and we will acknowledge this in the paper.

**Comment by FIN-JBarile** [comment]
@Dengaloo: I think you are referring to the MATRIX table, instead of the ESTIMATE table. The MATRIX table stores all the default values used for the Life History Tool, in which QB values are stored per species. QB values in said table are either based on available data in FishBase, and in the absence of data computed using Winf, temp, aspect ratio and food type. Correct? From my understanding in your explanations above, MaintQB is the latter. Correct? 

@agruss2: The MATRIX table should be in the the FishBase tables Jorrit has on hand. If not, please let me know. I modified the data dictionary in https://www.dropbox.com/s/92yo0733mlx7jw1/FishBase_DataDictionary.xls?dl=0. It now includes the Matrix table structure with short description of the QB columns.

**Comment by agruss2** [comment]
@Dengaloo @FIN-JBarile I am extending the deadline of this issue to March, 19th. Many thanks!

**Comment by agruss2** [comment]
@Dengaloo @FIN-JBarile There have not been any discussions on the estimation of parameters for OSMOSE during the past weeks. Hopefully, these discussions will resume next week, so that I can open new issues for Jorrit to estimate values for the remaining OSMOSE parameters. I am extending the deadline of this issue again. Thanks a lot.

**Comment by Dengaloo** [comment]
@agruss2 @FIN-JBarile : Maintenance QB needs a little bit of integral calculation; @agruss2 would you be able to do that? basically, MaintQB is the QB at Winf (see p. 833-834 of http://fishbull.noaa.gov/844/pauly.pdf). See also daily ration at page 447 of http://www.publish.csiro.au/mf/pdf/MF98015. So what is needed is to use the population Q/B/365 to get the daily food consumption per unit biomass, which is basically the gross food conversion efficiency (K1) = growth (dw/dt)/food ingested (daily ration); see equation 7 of http://www.publish.csiro.au/mf/pdf/MF98015. K1 and Winf are then plugged into equation (1) of http://www.publish.csiro.au/mf/pdf/MF98015, with the term Wt=Winf. You test by using the case in Figure 4 of http://fishbull.noaa.gov/844/pauly.pdf.

**Comment by agruss2** [comment]
@Dengaloo @FIN-JBarile Sounds good; I will not be able to do the integral calculation, so please do it. Please let me know when the estimates of QB and MaintQB are available in the MATRIX table so that I can open a new API issue for Jorrit. Many thanks!

**Comment by agruss2** [comment]
The bridge between FishBase/SeaLifeBase and OSMOSE now provides critical predation efficiency estimates. Therefore, the present issue can now be closed.
