### ISSUE TITLE
Create a basic UI to enter basic configuration 

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/fb-osmose-bridge#34]
Allow a basic user to enter the minimal information needed to build a valid OSMOSE configuration.

1. user goes to ```http://osmose.org/config```, the osmose configuration generator site	
1. fishbase-osmose bridge pre-populates basic information (e.g. functional groups names, time stamp, background functional groups)
1. ```optional```user customizes list of functional group name + focal species (group name has multiple focal species, e.g. "My functional group" with focal species "Ariopsis felis")
1. ```optional``` user customizes time step (1 value, e.g. 1 month)
1. ```optional``` user customizes list of background functional group names + focal species (group name has multiple focal species)
1. user clicks "generate configuration"
1. fishbase-osmose bridge dynamically creates the associated osmose configuration based on a default template in a zip archive. The zip file includes a readme file with instructions on how to further customize the configuration.
1. user downloads the generated osmose configuration as zip archive
1. ```optional``` user verifies and edits the generated osmose configuration 
1. user to save the customized osmose configuration (see #35)
1. user runs a osmose simulation using the customized configuration

Arnaud: what to do when traits are not available for a provided focal species? Deng: you can use the estimates table whenever traits are not available.

**Comment by FIN-JBarile** [comment]
#2 We can generate functional groups using attached reference table. We can provide functional groups for species occurring in the Gulf of Mexico, following this table. We can also generate the ESTIMATE table for these species. You can use these tables for generating list of species by functional groups, and their associated life history parameters from the ESTIMATE table.

However, note the field definitions of the ESTIMATE table attached. This means that the ESTIMATE table can only give you growth, trophic level, max. length TL, depth range and length-weight.

Note: attachement to be completed and to follow soon

**Comment by jhpoelen** [comment]
Thanks for your comment. I can see how storing predefined functional groups and related estimates can be useful to get started for a user. Following earlier discussions, I also imagine that users would want to tweak the functional group and pick their own list of focal species they'd like to use.

I am trying to understand how this related to this issue. Some questions: How would a user specify the functional group name and the focal species in this scenario? Would a user be able to add their own functional group/focal species combinations?

@agruss2 any thoughts?

**Comment by agruss2** [comment]
**(1) **What we discussed on Monday is that the OSMOSE user will query parameter estimates to the bridge between FishBase/SeaLifeBase and OSMOSE through a UI , BUT will do so after having determined himself/herself: 
(i) the focal functional groups of his/her OSMOSE model, and the different species making up each of these focal functional groups; 
(ii) the time step of his/her OSMOSE model; 
and (iii) the background functional groups of his/her OSMOSE model, and the different species making up each of these background functional groups. 


**(2) **This means that to get parameter estimates, the user will go to a website (e.g., http://osmose.org/config). Once the user is on the website, a UI will ask him/her to provide himself/herself the following information:
(i) A list of the focal functional groups represented in his/her OSMOSE model + a maximum of 2 reference species for each focal functional group; 
(ii) The number of time steps per year in his/her OSMOSE model; 
and (iii)  A list of the background functional groups represented in his/her OSMOSE model + a maximum of 4 reference species for each background functional group. 
Once all the above information has been entered, then the bridge between FishBase/SeaLifeBase and OSMOSE will be able to get parameter estimates for the OSMOSE user and will write all these parameter estimates in OSMOSE configuration CSV files. 


**(3) **A few comments on the above:

(i) The UI will have to remind the user that the name of focal functional groups should not include spaces nor underscores. For example, "CoastalOmnivores" is a valid focal functional group name, but not "Coastal omnivores" nor "Coastal_omnivores". 

(ii) The UI will ask the user to provide a maximum of 2 reference species, i.e., a maximum of 2 Latin names, for each focal functional group. For example, for the functional group "CoastalOmnivores", the user could provide the following Latin names: "Lagodon rhomboides" and "Monacanthus hispidus". Some focal functional groups may consist of only one species (e.g., the "RedGrouper" focal functional group in the OSMOSE model of the West Florida Shelf); in that case, the user will provide only one Latin name (i.e., "Epinephelus morio" in the case of "RedGrouper"). The UI should clearly mention to the user that he/she has to provide only one Latin name for those focal functional groups consisting of only one species. 
An existing routine in FishBase/SeaLIfeBase will check the validity of Latin names and correct some of them if necessary. FishBase/SeaLIfeBase's ESTIMATE table will be useful to fill the blanks: if some parameter estimates cannot be found for any of the reference species of a given functional group, then parameter estimates for a related species will be provided. 

(iii) Among the 2 reference species that will be defined for each focal functional group, the first one will be the "primary reference species", while the second one will be the "secondary reference species". The bridge between FishBase/SeaLIfeBase and OSMOSE will always look for parameter estimates for the primary reference species first; it will look for a given parameter estimate for the secondary reference species only if it cannot find that parameter estimate for the primary reference species. Then, if the bridge between FishBase/SeaLIfeBase and OSMOSE cannot find a given parameter estimate for both the primary and secondary reference species, it will make use of FishBase/SeaLIfeBase's ESTIMATE table to get that parameter estimate for a related species. 
The UI will have to clearly indicate to the user that the first reference species that the user indicates is the primary reference species, while the second reference species indicated is the secondary reference species. The UI will also provide a clear explanation of the meaning of "primary reference species" and "secondary reference species" to the user. 

(iv) The UI will have to remind the user that the name of background functional groups should not include spaces nor underscores. For example, "SmallMobileEpifauna" is a valid focal functional group name, but not "Small mobile epifauna" nor "Small_mobile_epifauna". 

(v) The UI will ask the user to provide a maximum of 4 reference species for each background functional group. These "reference species" can be Latin species names, Latin genus names, family names and/or order names. The rationale for that is that it may be very difficult to get 4 Latin species names for background functional groups such as "Microphytoplankton" or "Meiofauna" for instance. A maximum of 4 reference species rather than a maximum of 2 reference species will be required for background functional groups, because background functional groups are typically made of a much larger diversity of organisms than focal functional groups. 
Some background functional groups may consist of only one "species"; in that case, the user will provide only one reference species name. The UI should clearly mention to the user that he/she has to provide only one Latin name for those background functional groups consisting of only one "species".

**Comment by jhpoelen** [comment]
As agreed today, for now, we'll start with github pages.

**Comment by FIN-JBarile** [comment]
@agruss2 
Sharing screenshots of the UI for the Catch-MSY tool in FishBase, which might be of some help in drafting the layout for this UI.

[CatchMSY-UI.zip](https://github.com/jhpoelen/fb-osmose-bridge/files/220955/CatchMSY-UI.zip)

**Comment by agruss2** [comment]
@FIN-JBarile @jhpoelen 
I am going to send several drawings similar to the figures provided in the CatchMSY-UI.zip file.

**Comment by agruss2** [comment]
![step1](https://cloud.githubusercontent.com/assets/16559622/14613176/c8d58566-0560-11e6-92ad-f5095878773f.jpg)

**Comment by agruss2** [comment]
![step2](https://cloud.githubusercontent.com/assets/16559622/14613475/3e82ad6a-0562-11e6-9a6b-cfcfc5a0ac0f.jpg)

**Comment by agruss2** [comment]
![step3](https://cloud.githubusercontent.com/assets/16559622/14614281/0894015a-0566-11e6-9f26-1cc849bc58c7.jpg)

**Comment by agruss2** [comment]
![step4_1_1](https://cloud.githubusercontent.com/assets/16559622/14615281/7d5749c6-056a-11e6-9e0d-cbe2299be046.jpg)

**Comment by agruss2** [comment]
![step4_1_2](https://cloud.githubusercontent.com/assets/16559622/14616516/568c0380-0570-11e6-8631-ecbda792cc6d.jpg)

**Comment by agruss2** [comment]
![step4_2](https://cloud.githubusercontent.com/assets/16559622/14620013/1c4c6e48-0580-11e6-92af-d85a8baabe92.jpg)

**Comment by agruss2** [comment]
![step5](https://cloud.githubusercontent.com/assets/16559622/14620457/6b33444e-0582-11e6-9dde-194c33d4f793.jpg)

**Comment by agruss2** [comment]
![step6](https://cloud.githubusercontent.com/assets/16559622/14620709/dd1f1dde-0583-11e6-8ba3-2be376d98cca.jpg)

**Comment by agruss2** [comment]
![step7](https://cloud.githubusercontent.com/assets/16559622/14620856/ded12428-0584-11e6-862f-c9c9c175eaae.jpg)

**Comment by agruss2** [comment]
Once Step 7 has been completed, the bridge between FishBase/SeaLifeBase and OSMOSE will run. 
Ultimately, the OSMOSE user will get a zip file containing: (1) all the OSMOSE configuration files; and (2) a README file detailing which parameter estimates were obtained through the bridge between FishBase/SeaLifeBase and OSMOSE and which parameter estimates remain to be entered by the user.

**Comment by agruss2** [comment]
@FIN-JBarile @Dengaloo 
In OSMOSE, functional groups rather than individual species are considered. 
Species of a given focal functional group share the same habitat and are found over similar depth ranges, and they exhibit similar life history traits, body size ranges, diets and exploitation patterns. Species of a given background functional group share the same habitat and are found over similar depth ranges, and they exhibit similar life history traits, body size ranges and diets.  
Exploitation patterns refer here to the gears primarily targeting the species of the focal functional groups, and to the status of the species making up the focal functional group (e.g., overexploited).
Life history traits essentially refer to whether the functional group has a slow life history (slow growth, late sexual maturity, low natural mortality rate (over all ages)) or a fast life history (fast growth, early sexual maturity, high natural mortality rate (over all ages)).

**Comment by FIN-JBarile** [comment]
Static pages currently available through: http://fin-casey.github.io/step1.html (https://github.com/FIN-casey/FIN-casey.github.io.). We could not set up in the fb-osmose repo just yet. @jhpoelen is it where we are supposed to set things up for this?

This UI is pretty much still just a shell, just static pages and nothing drawing from the database yet. We need more time to explore to make it functional in the Github environment.

**Comment by agruss2** [comment]
Below, I am going to provide figures and comments, so that the UI that has been initiated can be improved. 
Steps 1 and 2 are good to me. 
The first figure that I am going to provide below is a suggestion for improvement of Step 3 when the option "Define functional groups for me" has been selected in Step 2.

**Comment by agruss2** [comment]
![step3_1](https://cloud.githubusercontent.com/assets/16559622/15056446/3c7ae690-12d7-11e6-9a86-c2ab6461d683.jpg)

**Comment by agruss2** [comment]
**Comments on Step 3 when the option "Define functional groups for me" has been selected in Step 2:**
**(1)** I would like the UI to shade a deselected functional group. For instance, if the user deselects "Amberjacks", the whole row for "Amberjacks" should be shaded. Could this easily be implemented?  
**(2) **I would like the UI to shade a deselected species. For instance, if the user deselects "Seriola dumerili", then "Seriola dumerili" should be shaded in the "Species" column of the "Amberjacks" functional group. Could this easily be implemented?                                  
**(3)** I would like the "Species" column to provide the order, family and vernacular name of each species. For instance, something like "Perciformes - Carangidae - Seriola dumerili - Greater amberjack" should be provided instead of "Seriola dumerili" only. The reason why I did not write this down above is that I had limited space to do so. 
The rationale here is that, for those functional groups that belong to very low trophic levels (e.g., plankton groups, low-trophic level benthic groups), we would prefer the bridge between FishBase/SeaLifeBase and OSMOSE to provide family names or order names instead of species names, for practical reasons. Think, for instance, of a "Microzooplankton" group; it would be more convenient for the user to get information such as "Paracalanidae", "Oncaea" and "Oithona" from the bridge between FishBase/SeaLifeBase and OSMOSE rather than the Latin names of the thousands of species that can make up the "Microzooplankton" group. 
**(4) **This is a repeat of the previous comment: for those functional groups that belong to very low trophic levels (e.g., plankton groups, low-trophic level benthic groups), we would prefer the bridge between FishBase/SeaLifeBase and OSMOSE to provide family names or order names instead of species names, for practical reasons. Think, for instance, of a "Microzooplankton" group; it would be more convenient for the user to get information such as "Paracalanidae", "Oncaea" and "Oithona" from the bridge between FishBase/SeaLifeBase and OSMOSE rather than the Latin names of the thousands of species that can make up the "Microzooplankton" group.

**Comment by agruss2** [comment]
Steps 4 and 5 are good to me.
The figure that I am going to provide now is a suggestion for improvement of Step 6.

**Comment by agruss2** [comment]
![step6](https://cloud.githubusercontent.com/assets/16559622/15057767/26669104-12de-11e6-9204-97faae7b9754.jpg)

**Comment by agruss2** [comment]
Now, here is my suggestion for the final page of the UI (which comes right after Step 6).

**Comment by agruss2** [comment]
The last figure that I am providing today is a suggestion for improvement of Step 3 when the option "Let me define functional groups" has been selected in Step 2. 
![step3_2](https://cloud.githubusercontent.com/assets/16559622/15059502/ac1ec92e-12e8-11e6-8778-6bf2b72ec430.jpg)

**Comment by FIN-casey** [comment]
Most of the changes in the UI are already implemented except the last image above. 

The Step 3 when the option "Define functional groups for me" has been updated. The Select/Deselect and Species column have checkboxes to choose which are included. When deselecting a functional group, the whole row gets shaded, and the checkbox and radio buttons for that functional group get disabled.

The Step 6 and the final Step has also been updated.

**Comment by FIN-casey** [comment]
The UI of Step 3: Define Functional Groups is now implemented.

Step 1 and Step 3: Reorganize functional groups are now more interactive. 

In Step 1, I put radio buttons to choose between Ecosystem or Country. When the user choose either one, the inputs for the unselected will be disabled, and the inputs will reset. Sub-country and FAO Area are now working based on chosen Country.

![image](https://cloud.githubusercontent.com/assets/18322815/16148829/c29dfc54-34be-11e6-868a-f919c1fde22d.png)

In Step 3: Reorganize Functional Groups, there are developments
The table is now completely filled with details. Size Category, Habitat and Depth details are called from fishbaseapi of ropensci.

![image](https://cloud.githubusercontent.com/assets/18322815/16149041/87538bc6-34c0-11e6-8c33-bc13f5de9b5a.png)

Saving details of every step to a formatted text such as csv or JSON is under development.

**Comment by jhpoelen** [comment]
@FIN-casey looks great! Is there a place we can play around with it? I'd suggest to organize a meeting in which @agruss2 can provide feedback and identify next steps.

**Comment by FIN-casey** [comment]
The modified version is already implemented in github. It can be access in http://fin-casey.github.io/step1.html.

**Comment by agruss2** [comment]
@FIN-casey @jhpoelen @FIN-JBarile @Dengaloo 
Here are my comments on July, 17th 2016:

(1) Step 1 – If I do not select any ecosystem or any combination of a country and FAO area and press Proceed, then the web service proceeds to next step. A message (in red) should pop up when the user does not select any ecosystem or any combination of a country and FAO area and press Proceed  (“Please select an ecosystem or a combination of a country and FAO area”).

(2) Step 3 after having chosen the option “Define functional groups for me”: (i) one cannot use the Edit button currently; (ii) one cannot type the name of a species (Latin name, vernacular name, family name or order name) currently; (iii) one cannot use the Plus button currently; and (iv) one cannot sort functional groups by size, habitat or depth currently.  

(3) Step 3 after having chosen the option “Let me define functional groups”: (i) one cannot use the Edit button currently; (ii) one cannot type the name of a species (Latin name, vernacular name, family name or order name) currently; and (iii) one cannot use the Plus button currently.  
	
(4) Step 3 after having chosen the option “Define functional groups for me”:  Please replace “and type the name of species” with: “and type the name of the species”. 

(5) Step 6 – Please replace “if your OSMOSE model has monthly time step” with: “if your OSMOSE model has a monthly time step”; and “if your OSMOSE model has quarterly time step” with: “if your OSMOSE model has a quarterly time step”. 

(6) Step 6 – If I do not enter a value and press Proceed, then the web service proceeds to next step. A message (in red) should pop up when the user does not enter a value and press Proceed (“Please indicate the time step of your OSMOSE model”). 

(7) Download configuration files for your OSMOSE model – Currently, one does not get any zip file when pressing "Download configuration files".

**Comment by agruss2** [comment]
I am closing this issue today, because we now have a draft of UI, and the different items mentioned above are addressed in separate issues.
