### ISSUE TITLE
allow for specifying to use age or size for recruitment size parameter

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/fb-osmose-bridge#5]
As shared by Arnaud Gruss by email:
In the “osm_param-fishing.csv” file, for each high trophic level (HTL) group, both an age of recruitment into the fisheries (“mortality.fishing.recruitment.age.sp” parameter) and a size of recruitment into the fisheries (“mortality.fishing.recruitment.size.sp” parameter) are provided. If a value is given to both the “mortality.fishing.recruitment.age.sp” and “mortality.fishing.recruitment.size.sp” parameters, then OSMOSE will use only the information provided for the “mortality.fishing.recruitment.size.sp” parameter, since this information appears last in the “osm_param-fishing.csv” file.  Therefore, it is necessary to indicate that the “mortality.fishing.recruitment.age.sp” parameter or the “mortality.fishing.recruitment.size.sp” parameter is “null”, depending on the information that the user wants OSMOSE to use; for example, if the user wants OSMOSE to use an age of recruitment into the fisheries for Scomberomorus cavalla (sp0), then “mortality.fishing.recruitment.age.sp0” must be set to, say, 0.5, while the “mortality.fishing.recruitment.size.sp0” parameter must be set to “null”.

**Comment by agruss2** [comment]
The information entered in the  “osm_param-fishing.csv” file does not matter, since FishBase/SeaLifeBase will not provide information to populate this file. 
What matters more is that, in the “osm_param-species.csv” file, for each high trophic level (HTL) group, both an age at sexual maturity ("species.maturity.age.sp" parameter) and a size at sexual maturity (“species.maturity.size.sp” parameter) are provided. If a value is given to both the "species.maturity.age.sp" and “species.maturity.size.sp” parameters, then OSMOSE will use only the information provided for the “species.maturity.size.sp” parameter, since this information appears last in the “osm_param-species.csv” file. Therefore, it is necessary to indicate that the "species.maturity.age.sp" parameter or the “species.maturity.size.sp” parameter is “null”, depending on the information that the user wants OSMOSE to use; for example, in the West Florida Shelf case study, if the user wants OSMOSE to use a size at sexual maturity for Scomberomorus cavalla (sp0), then “species.maturity.age.sp0” must be set to "null", while the “species.maturity.size.sp0” parameter must be set to 73.4.
