### ISSUE TITLE
On clicking download button, retrieve generated osmose_config.zip

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/fb-osmose-bridge#61]
For more information see alt 3. at http://github.com/jhpoelen/fb-osmose-bridge  .

**Comment by agruss2** [comment]
@FIN-casey  Jorrit wants you to consider Option 3 so that his configuration API can now communicate with your wizard. 
@jhpoelen Please create an issue to explain clearly what you have in mind regarding the communication between your configuration API and Casey's wizard.

**Comment by FIN-casey** [comment]
The download button in the last step now works. Thanks to @jhpoelen for giving me an example.
Please check if the downloaded osmose_config.zip is accurate based on the selected group and species.

**Comment by jhpoelen** [comment]
@FIN-casey I just created change to https://github.com/jhpoelen/fb-osmose-bridge-js to address the issue that @agruss2 saw today. With this version, the dynamic configuration should be downloaded.

**Comment by FIN-casey** [comment]
@jhpoelen I updated the copy of your library in where the wizard is linked. 
I implemented a status label in the last step of the wizard. When the user press submit, the label will show **"Preparing configuration..."**.
Then when the processing is done, it will show **"Done preparing configuration"**. Below the label will be a link "Click here to download". When clicking the link, the browser will download the osmose_config.

@agruss2 Please test.

**Comment by agruss2** [comment]
@FIN-casey 
I just made a test and I love the changes that you have introduced in the "Download configuration files for your OSMOSE model" page. Let me have a deeper look at the content of the "osmose_config.zip" and then come back to you.

**Comment by agruss2** [comment]
@FIN-casey @jhpoelen 
I had a deep look at the content of the "osmose_config.zip" file. Everything makes perfect sense there, excellent job Casey and Jorrit !
A few comments now:
(1) When the time is ripe, I will write the README file that is mentioned in the last page of the UI; 
(2) Actually, it would make more sense to provide classes rather than orders for background functional groups - I will write an issue about this very soon; 
and, more importantly:
(3) Could we please test the "osmose_config.zip" file for background functional groups as well now? 
Currently, the "osmose_config.zip" file provides parameter values (dummy ones at present) for 4 focal functional groups. Could the zip file also provide parameter values (dummy ones) for one background functional group ? Please try with the following functional group:
* Bivalves (class: Bivalvia)
* Reference species: Donax variabilis, and Argopecten gibbus

**Comment by jhpoelen** [comment]
@agruss2 glad to hear that the download is now working for you. Suggest to close this issue and open a new issue to address the background group issue.
