### ISSUE TITLE
Enhancing the API so that it provides some first OSMOSE parameter values

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#73]
@jhpoelen 
The time is ripe to enhance the API so that it provides estimates for "simple" OSMOSE parameters to be incorporated in the CSV files of the "osmose_config.zip" file. The simple OSMOSE parameters I am referring to are the following (https://github.com/jhpoelen/fb-osmose-bridge/blob/master/src/main/resources/com/github/jhpoelen/fbob/fishbase-mapping.csv):
species.lifespan.sp
species.K.sp
species.lInf.sp
species.t0.sp
species.length2weight.condition.factor.sp
species.length2weight.allometric.power.sp
species.maturity.size.sp
species.maturity.age.sp
species.sexratio.sp
predation.ingestion.rate.max.osmose.sp
predation.predPrey.stage.threshold.sp
predation.accessibility.stage.threshold.sp
plankton.TL.plk
plankton.size.min.plk
plankton.size.max.plk

Please let me know when you have made some progress on this front; I will then use the wizard, download the "osmose_config.zip" file to thoroughly check its content, and let you know my thoughts. 

Many thanks.

**Comment by jhpoelen** [comment]
@agruss2 Thanks for your detailed issue description. I included necessary improvements to ensure the correct mapping of provided parameters and extended test cases to check the provided implementation (see https://github.com/jhpoelen/fb-osmose-bridge/blob/master/src/test/java/com/github/jhpoelen/fbob/TraitFinderIntegrationTest.java). Please confirm that the mapping is as expected.

**Comment by agruss2** [comment]
@jhpoelen 
Thanks a lot for having worked on this. 
I used the wizard to see if the changes that you have introduced lead to the definition of relevant values for "simple" OSMOSE parameters, but unfortunately ran through a bug described in #77. 
Please try to solve issue #77. I will then reuse the wizard to download a config zip file so as to check that the simple OSMOSE parameter values provided by the API make sense.

**Comment by agruss2** [comment]
@jhpoelen 
Thanks a lot for having worked on this; this is a good start. 
I went through all the steps and downloaded an osmose config zip file. 
Here are the errors that I have noticed:
(1) species.lifespan.sp0 was set to 0, while it should be greater than 0; 
(2) species.maturity.size.sp1 and species.maturity.size.sp2 were both set to 0, while they should both be greater than 0; 
(3) species.maturity.age.sp0, species.maturity.age.sp1 and species.maturity.age.sp2 do not appear in the "osm_param-species.csv" file, while they should; 
(4) species.sexratio.sp0, species.sexratio.sp1 and species.sexratio.sp2 were all set to 0, while they should all be greater than 0; 
(5) predation.accessibility.stage.threshold.sp0, predation.accessibility.stage.threshold.sp1 and predation.accessibility.stage.threshold.sp2 were all set to 0, while they should all be greater than 0; 
(6) plankton.size.max.plk0 was set to 0, while it should be greater than 0; 
and 
(7) plankton.size.min.plk0 was set to 0, while it should be greater than 0. 

I think that I know why we get these results. This is because, currently, the API considers only 1 species for each functional group to derive some parameter values. This should be altered so that we get relevant values for the different parameters of all functional groups. Issue #59 states: "List of up to 100 species provided for an order will be ranked by decreasing data richness. The species will be extracted from the fishbase api." This needs to be implemented so that the API can get a long list of species for each functional group instead of only one single species. Could you please work on this issue with @FIN-JBarile and @FIN-casey as soon as possible?

**Comment by jhpoelen** [comment]
@agruss2 Thank your for your feedback.

Please provide the functional groups and associated species that you used to generate your result, including the fishbase spec code if possible.

**Comment by jhpoelen** [comment]
@agruss2 I've made it so that defaults are applied on the group level. Previously, the defaults were applied on the species level.

consider group X that contains species A and species B. Fishbase does *not* have a value for trait T for species A, but it does have a value for trait T for species B.

So previously, if value for trait T was not available for species A, the api would place the default instead. 

Now, if a value was not available for species A, the api considers the next species in the group (i.e. species B) and attempts to retrieve the value for trait T for that species. If all species have been exhausted, the api will place the default value for trait T.

Once @FIN-JBarile and @FIN-casey  implement #59 and provide the ordered list to the API, appropriate trait values should be found in the resulting osmose configuration archive.

@agruss2 please confirm that the behavior is as expected.

**Comment by agruss2** [comment]
@jhpoelen 
Thanks a lot, this is excellent !

You are describing very well what we want to do here. 

So, I went through all the steps and downloaded a new osmose config zip file.
I noticed that, now that the strategy that you are describing is implemented, we are obtaining fewer errors. Here are the errors that I have noticed this time:
(1) species.lifespan.sp0 was set to 0, while it should be greater than 0;
(2) species.maturity.size.sp2 was set to 0, while it should be greater than 0;
(3) species.maturity.age.sp0, species.maturity.age.sp1 and species.maturity.age.sp2 do not appear in the "osm_param-species.csv" file, while they should;
(4) species.sexratio.sp0, species.sexratio.sp1 and species.sexratio.sp2 were all set to 0, while they should all be greater than 0;
(5) predation.accessibility.stage.threshold.sp2 was set to 0, while it should be greater than 0;
(6) plankton.size.max.plk0 was set to 0, while it should be greater than 0;
and
(7) plankton.size.min.plk0 was set to 0, while it should be greater than 0.

**Comment by jhpoelen** [comment]
@agruss2 thanks for your details. 

Please provide a sealifebase/fishbase urls, species names and expected value for each of the traits you mentioned.

Also, please provide the functional groups and their taxa.

**Comment by jhpoelen** [comment]
@agruss2 While I am waiting for your details on specifics of expected "greater than zero" values for your specific test, I am able to address two items.

Re: ```(1) species.lifespan.sp0 was set to 0, while it should be greater than 0;```
I noticed that you  changed the default from 0.0 to 0.5. The changes broke the build and were not propagated. You should have received an email about this from travis. I fixed the issue yesterday, and the expected default should now appear. 

Re ```(3) species.maturity.age.sp0, species.maturity.age.sp1 and species.maturity.age.sp2 do not appear in the "osm_param-species.csv" file, while they should;```
This property has been added. 

Re ```(5) predation.accessibility.stage.threshold.sp2 was set to 0, while it should be greater than 0;```
According the the fishbase-mapping.csv file, this property is using an unsupported column name selected (discussed in #76). So, I would expect only observed default values for this property to appear. 

This leaves:

(2) species.maturity.size.sp2 was set to 0, while it should be greater than 0;
(4) species.sexratio.sp0, species.sexratio.sp1 and species.sexratio.sp2 were all set to 0, while they should all be greater than 0;
(6) plankton.size.max.plk0 was set to 0, while it should be greater than 0;
and
(7) plankton.size.min.plk0 was set to 0, while it should be greater than 0.

In order for me to resolve these issue, I need: 
1. the fishbase species id and name 
2. the expected osmose property value (e.g. 0.1234, instead of "greater than 0")
3. a link to the fishbase / sealifebase page that reports the expected osmose property

Thanks you for your patience and providing the details needed to nail down these important issues.

**Comment by jhpoelen** [comment]
@agruss2 please note the updated comments above.

**Comment by agruss2** [comment]
@jhpoelen 
Here is the selection that I made in the wizard:
* sp0: 
Functional Group: Amberjacks
Focal Functional Group: Yes
Species: Seriola dumerili; Seriola fasciata; Seriola zonata

* sp1:
Functional Group: SmallPelagics
Focal Functional group: Yes
Species: Sardinella aurita; Harengula jaguana; Opisthonema oglinum; Decapterus punctatus

* sp2:
Functional Group: KingMackerel
Focal Functional Group: Yes
Species: Scomberomorus cavalla

* plk0:
Functional Group: RedGrouper
Background Functional Group: Yes
Species: Epinephelus morio

**Comment by jhpoelen** [comment]
@agruss2 thanks again for your detailed feedback and your patience.

I have documented your observations in separate issues in an attempt to organize our work. This is why I am closing this issue. If you find any new suspicious values in generated osmose configuration file, please open a separate issue.
