### ISSUE TITLE
Cannot download the zip file

### ISSUE THREAD

**Issue by agruss2** [jhpoelen/fb-osmose-bridge#77]
@jhpoelen @FIN-casey 
For some reason, one cannot download the zip file currently. 
See the following snapshot:

> 
![issue_sep26_2016](https://cloud.githubusercontent.com/assets/16559622/18856589/a21fd22e-8421-11e6-843b-fada8f1e1475.jpg)

To sum up what is going on here: I went through all the steps of the wizard without facing any troubles. However, once the configuration zip file is ready, there is no way to click on "Click here to download" to download the config zip file. 
This is happening today, after Jorrit has made some changes in the API to get values for "simple" OSMOSE parameters. Do you guys understand what his going on here? Could you please fix this bug? 
Many thanks.

**Comment by jhpoelen** [comment]
@agruss2 thanks for sharing this. Root cause of this was that some species in fishbase do not have entries in specific tables (e.g. Seriola dumerili / http://fishbase.org/summary/1006 / https://fishbase.ropensci.org/fecundity?SpecCode=1006). On requesting the data through the fishbase api, an error code is generated, and the generation of the zip file stopped with an error.

Now, on encountering errors, an log entry is generated describing the issue and the generation proceeds.

**Comment by jhpoelen** [comment]
Just used the wizard to create attached configuration file. Please close this issue if you can reproduce.
[osmose_config.zip](https://github.com/jhpoelen/fb-osmose-bridge/files/494524/osmose_config.zip)

**Comment by agruss2** [comment]
@jhpoelen 
It is indeed working now; many thanks. Closing this issue now.
