### ISSUE TITLE
Unexpected value for species.maturity.size.sp for Scomberomorus cavalla (FishBase ID: 120)

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/fb-osmose-bridge#80]
In #73, @agruss2 shared that the expected value for species.maturity.size.sp for  Scomberomorus cavalla (FishBase ID: 120) is 63.3 . However, the actual value was: 0.0 .

I was able to reproduce the result. Also, I found that the value 0.0 appears because only the first row in the fishbase table ```maturity``` contained a null value for the ```Lm``` column.

On inspection of the values retrieved from the fishbase api (see https://fishbase.ropensci.org/maturity?SpecCode=120&limit=5000), I found that 13 rows appeared. However, the value 63.3 does not appear. This is why, I suspect that the defined mapping in ```fishbase-mapping.csv``` might needs updating.

Also, I've changed the bridge implementation to map the first non-null value in the results. 
 
This change resulting in the line ```species.maturity.size.sp2;50.0``` to appears in osm_params-species.csv . The values seems to be consistent with those found in http://fishbase.org/Reproduction/MaturityList.php?ID=120 rather than the summary page http://fishbase.org/summary/120 .

@agruss2 The reported expected value could not be found with the mapping constraints defined in the fishbase-mapping.csv . Please revise the mapping or suggest alternative implementation.

**Comment by agruss2** [comment]
@jhpoelen I thought about to best update the fishbase-mapping.csv (see https://github.com/jhpoelen/fb-osmose-bridge/blob/master/src/main/resources/com/github/jhpoelen/fbob/fishbase-mapping.csv). 
To my mind, this is the only thing I needed to do to address the present issue. 
If you need anything else from me, please let me know. Otherwise, please close the present issue.
