### ISSUE TITLE
introduce a way to map a group name to a specific species name / fishbase species id

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/fb-osmose-bridge#9]
as suggested by @agruss2 

Most users would want to decouple the groupname from the name of the examplar species.

**Comment by agruss2** [comment]
@jhpoelen 
The "osm_param-species.csv" file indicates the name of each focal functional group using the "species.name.sp" keys. For instance, The "species.name.sp7" is associated with the "CoastalOmnivores" value. 
I suggest that we inntroduce new keys in the "osm_param-species.csv" file, which we would call "species.reference.name.sp". For instance, "species.reference.name.sp7" would be "LagodonRhomboides". 
Please let me know if you like this idea. If so, I'll provide you with an updated version of the "osm_param-species.csv" file, so that you can test the bridge between FishBase/SeaLifeBase and OSMOSE with this new version of the file.

**Comment by agruss2** [comment]
@jhpoelen @FIN-JBarile @Dengaloo
In the "osm_param-species.csv" OSMOSE configuration file, I introduced new keys called "species.reference.name.sp". For instance, "species.reference.name.sp7" is "LagodonRhomboides".
The new version of the "osm_param-species.csv" OSMOSE configuration file can be found in Dropbox in the "OSMOSE configuration files" folder. 
During our next phone call, we will need to discuss something important: If parameter estimates are unavailable for a reference species, we need to make sure that the bridge between FishBase/SeaLifeBase gets the missing parameter estimates from related species.

**Comment by jhpoelen** [comment]
@agruss2 Sound like good way to decouple the functional name from a focal species name. I would imagine that these pairs would be provided by the user. As far as the getting estimates from related species, I can imagine a couple of methods: resolve the focal species name, extract the genus, and see whether there's other species around in that genus. Alternatively, a more direct approach can be applied by making an exhaustive list of species that are known to overlap or share specific traits.

**Comment by jhpoelen** [comment]
@agruss2 suggest to turn the names into a list of names, so that fall-back names can be used if trait are not available for the primary name. (e.g. ```LagodonRhomboides,AriopsisFelis```, instead of ```LagodonRhomboides```).

**Comment by FIN-JBarile** [comment]
Please study the file that we propose for functional groups definitions, and tell us if that will work for this purpose. 

Note: This is Deng and Skit responding together.

**Comment by jhpoelen** [comment]
I am assuming the functional group definition is part of another thread: please see https://github.com/jhpoelen/fb-osmose-bridge/issues/34#issuecomment-209213929 and my related comment.
